language: elixir
elixir:
  - 1.6.6
  - 1.7.1
otp_release:
  - 20.3
  - 21.0
before_script:
  - MIX_ENV=test mix compile --warnings-as-errors
  - travis_wait mix dialyzer --plt
script:
  - mix credo --strict
  - mix format --check-formatted
  - mix dialyzer --halt-exit-status
sudo: required
dist: trusty
cache:
  directories:
    - _build
    - deps
